version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: mlflow_server
    ports:
      - "5001:5001"
    environment:
      - ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow
    command: >
      mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/artifacts

volumes:
  mlflow_data:

